home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/delete/', views.delete_task, name='task_delete'),
    path('<int:id>/complete/', views.complete_task, name='task_complete'),
    path('<int:id>/not-complete/', views.not_complete_task, name='task_not_complete'),
    path('register/', views.register, name='register'),
    path('register_success/', views.register_success, name='register_success'),
]

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class TaskManager(models.Manager):
    def create_task(self, description, creator):
        task = creator.tasks.create(description=description, creator=creator)
        return task
class Task(models.Model):
    description = models.CharField(max_length=300)
    is_complete = models.BooleanField(default=False)
    creator = models.ForeignKey("Profile", on_delete=models.CASCADE)

    objects = TaskManager()

    def __str__(self):
        return self.description

class Team(models.Model):
    name = models.CharField(max_length=50)
    members = models.ManyToManyField("Profile")

    def __str__(self):
        return self.name

# Extension of default Django User class for storing
# each user's tasks
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    tasks = models.ManyToManyField("Task")

    def __str__(self):
        return self.user.username

# Basically we are hooking the create_user_profile and save_user_profile methods to the User model, 
# whenever a save event occurs. This kind of signal is called post_save.
# https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html#onetoone

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

home/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Task, Profile

class AddTaskForm(forms.Form):
    description = forms.CharField(max_length=300, required=True)

    def clean_description(self):
        data = self.cleaned_data['description']
        if len(data) >= 300:
            raise ValidationError('Task description too long')
        
        return data

class UserCreationForm(UserCreationForm):
    first_name = forms.CharField(max_length=20, required=True)
    last_name = forms.CharField(max_length=20, required=True)
    email = forms.EmailField(label="Email address", required=True, help_text="Required")
    

    class Meta:
        model = User
        fields = ("first_name", "last_name", "username", "email", "password1", "password2")

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("That user is already taken")
        return username

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.email = self.cleaned_data["email"]
        user.username = self.clean_username()
        if commit:
            user.save()
        return user

class ReassignTaskForm(forms.Form):
    id = forms.IntegerField(required=True, widget= forms.TextInput(attrs={'readonly': 'readonly'}))
    email = forms.EmailField(required=True)

    def clean_id(self):
        task_id = self.cleaned_data['id']
        tasks = Task.objects.filter(id=task_id)
        if tasks.count() != 1:
            raise ValidationError('Invalid Task ID')
        return task_id
    
    def clean_email(self):
        email = self.cleaned_data['email']
        users = Profile.objects.filter(user__email=email)
        if users.count() == 0:
            raise ValidationError('User with that email was not found')
        elif users.count() > 1:
            raise ValidationError('There are multiple users with that email')
        return email

home/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Task, Profile
from .forms import AddTaskForm, UserCreationForm, ReassignTaskForm
from django.shortcuts import redirect
from django.contrib import messages
from django.contrib.messages import get_messages
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    if request.user.is_authenticated:
        user_profile = Profile.objects.get(user=request.user)
        tasks = user_profile.tasks.filter(is_complete=False)
        completed_tasks = user_profile.tasks.filter(is_complete=True)
    else:
        tasks = None
        completed_tasks = None
    
    # If True, modal will appear. Used for error validation on Reassign Task Form
    show_reassign_modal = False
    old_task_id = ''

    if request.method == 'POST':
        if 'add-task' in request.POST:
            add_task_form = AddTaskForm(request.POST)

            if add_task_form.is_valid():
                description = add_task_form.cleaned_data['description']
                task = Task.objects.create_task(description, user_profile)
                task.save()
            
            reassign_form = ReassignTaskForm()

        elif 'reassign-task' in request.POST:
            reassign_form = ReassignTaskForm(request.POST)
            if reassign_form.is_valid():
                task_id = reassign_form.cleaned_data['id']
                reassign_email = reassign_form.cleaned_data['email']

                ### Reassign Task logic ###
                task = Task.objects.get(id=task_id)
                # Remove associtation with current Profile
                user_profile.tasks.remove(task)
                # Get new profile
                new_profile = Profile.objects.get(user__email=reassign_email)
                # Create association with new user
                new_profile.tasks.add(task)
                # Save
                task.save()
                new_profile.save()

                # Send successful Django message
                messages.add_message(request, messages.INFO, f'Task "{task.description}" (#{task_id}) reassigned to {reassign_email}')
            else:
                show_reassign_modal = True
                old_task_id = reassign_form.data['id']
            
            add_task_form = AddTaskForm()
    else:
        add_task_form = AddTaskForm()
        reassign_form = ReassignTaskForm()

    context = {
        'form': add_task_form,
        'reassign_form': reassign_form,
        'tasks': tasks,
        'completed_tasks': completed_tasks,
        'messages': get_messages(request),
        'show_reassign_modal': show_reassign_modal,
        'old_task_id': old_task_id,
    }

    return render(request, 'index.html', context)

@login_required(login_url='login')
def delete_task(request, id):
    print(request.user)
    task = Task.objects.get(id=id)
    # Check requesting user is assigned this task
    if task.profile_set.filter(user=request.user).count() > 0:
        task.delete()
    else:
        messages.add_message(request, messages.ERROR, 'You do not have permission to delete that task.')
    return HttpResponseRedirect('/')

@login_required(login_url='login')
def complete_task(request, id):
    task = Task.objects.get(id=id)
    if task.profile_set.filter(user=request.user).count() > 0:
        task.is_complete = True
        task.save(update_fields=['is_complete'])
    else:
        messages.add_message(request, messages.ERROR, 'You do not have permission to mark that task complete.')
    return HttpResponseRedirect('/')

@login_required(login_url='login')
def not_complete_task(request, id):
    task = Task.objects.get(id=id)
    if task.profile_set.filter(user=request.user).count() > 0:
        task.is_complete = False
        task.save(update_fields=['is_complete'])
    else:
        messages.add_message(request, messages.ERROR, 'You do not have permission to mark that task not complete.')
    return HttpResponseRedirect('/')

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('register_success')
    else:
        form = UserCreationForm()

    return render(request, 'registration/register.html', {'form': form})

def register_success(request):
    return render(request, 'registration/register_success.html')

home/templates/index.html
{% extends "base.html" %}

{% block content %}
<section class="content-section">
  <div class="container">

    <!-- Jumbotron Header -->
    <div class="jumbotron">
      <h1 class="display-4">Hello{% if user.first_name %}, {{ user.first_name }}{% endif %}!</h1>
      <p class="lead">Welcome to Simply Todo. You can add tasks in the box below. Click the checkbox to mark a task complete. You can also reassign tasks to other Simply Todo users by clicking the arrow.</p>
      {% if not user.is_authenticated %}
      <br>
      <a class="btn btn-primary btn-lg btn-block" href="{% url 'register' %}" role="button">Register</a>
      <a class="btn btn-primary btn-lg btn-block" href="{% url 'login' %}" role="button">Login</a>
      {% endif %}
    </div>
    <hr>

    <!-- Message alerts -->
    {% for message in messages %}
    <div class="alert alert-primary alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <hr>
    {% endfor %}

    <!-- Add task form -->
    {% if user.is_authenticated %}
    {% if form.errors %}
      <div class="alert alert-warning">
        Your task description is too long.
      </div>
    {% endif %}
    <form class="form-group" action="." method="post">
      {% csrf_token %}
      <div class="input-group">
        {% load home_extras %}
        {{ form.description|addcss:"form-control form-control-lg" }}
        <div class="input-group-append">
          <button class="btn btn-outline-primary" type="submit" name="add-task">Add Task</button>
        </div>
      </div>
    </form>
    <hr>

    <!-- List of uncomplete tasks -->
    {% for task in tasks %}
    <div class="form-group">
      <div class="input-group">
        <div class="input-group-prepend">
          <span class="input-group-text">{{ task.creator.user }}</span>
        </div>
        <input type="text" class="form-control form-control-lg" value="{{task.description}}" readonly>
        <div class="input-group-append">
          <div class="input-group-text">
            <input type="checkbox" onclick="window.location.href='{% url 'task_complete' task.id %}'">
          </div>
          <button type="button" class="btn btn-outline-secondary input-group-text dropdown-toggle dropdown-toggle-split" data-toggle="dropdown">
            <span class="sr-only">Toggle Dropdown</span>
          </button>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="#reassignModal" data-toggle="modal" data-id="{{task.id}}">Reassign</a>
            <div role="separator" class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'task_delete' task.id %}">Delete</a>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}

    <!-- List of complete tasks -->
    {% if completed_tasks %}
    <hr>
    <p>
      <button class="btn btn-secondary" type="button" data-toggle="collapse" data-target="#collapseComplete">
        Show Completed
      </button>
    </p>
    <div class="collapse" id="collapseComplete">
      {% for task in completed_tasks %}
      <div class="form-group">
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text">{{ task.creator.user }}</span>
          </div>
          <input type="text" class="form-control form-control-lg" value="{{task.description}}" readonly>
          <div class="input-group-append">
            <div class="input-group-text">
              <input type="checkbox" checked="checked" onclick="window.location.href='{% url 'task_not_complete' task.id %}'">
            </div>
            <button type="button" class="btn btn-outline-secondary input-group-text dropdown-toggle dropdown-toggle-split" data-toggle="dropdown">
              <span class="sr-only">Toggle Dropdown</span>
            </button>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url 'task_delete' task.id %}">Delete</a>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>

    <!-- Reassignment modal -->
    {% include 'reassign_modal.html' with form=reassign_form %}
    {% endif %}
    {% else %}

    <!-- Not logged in -->
    <div class="text-center">
      <img src="https://msu.edu/_assets/images/homepage-heroes/spring-west-circle.JPG" class="img-fluid">
    </div>
    {% endif %}
  </div>
</section>
{% endblock %}

{% block scripts %}
{% if show_reassign_modal %}
<script type="text/javascript">
  var modal = $('#reassignModal');
  modal.removeClass('fade');
  modal.modal('show');
  modal.find('#id_id').val({{ old_task_id }});
  modal.addClass('fade');
</script>
{% endif %}
{% endblock %}

home/templates/reassign_modal.html
<!-- Modal -->
<div class="modal fade" id="reassignModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Reassign Task</h5>
        <button type="button" class="close" data-dismiss="modal"></button>
      </div>
      <form id="reassign-form" action="." method="post"> {% csrf_token %}
        <div class="modal-body">
          {% if form.errors %}
          <div class="alert alert-warning">
            <h4 class="alert-heading">Unable to reassign task</h4>
            {{ form.email.errors }}
            {{ form.id.errors }}
          </div>
          {% endif %}
          <p class="model-text">Enter the email for the user you would like to reassign this task to.</p>
            <div class="form-group">
              <label for="{{ form.id.id_for_label }}" class="col-form-label">Task ID:</label>
              {% load home_extras %}
              {{ form.id|addcss:"form-control"}}
              <label for="{{ form.email.id_for_label }}" class="col-form-label">Email:</label>
              {{ form.email|addcss:"form-control" }}
            </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary" name="reassign-task">Reassign</button>
        </div>
      </form>
    </div>
  </div>
</div>